server:
  port: 8888
spring:
  datasource:
    username: root
    password: Root123!
    url: jdbc:mysql://106.12.111.202:3306/cinema?useUnicode=true&characterEncoding=utf-8&useSSL=false
  application:
    name: my-film-project
mybatis:
  typeAliasesPackage: com.film.**.mappers
  mapper-locations: classpath:mapper/**/**.xml
